-- +goose Up

-- Integer flags and timestamps retain the existing Go and wire formats.

-- Nullable SQLite text keys use UNIQUE because PostgreSQL primary keys reject NULL.

CREATE EXTENSION IF NOT EXISTS pg_trgm;

CREATE EXTENSION IF NOT EXISTS unaccent;

CREATE TABLE analytics_events (
    event_id TEXT UNIQUE,
    event_type TEXT NOT NULL,
    timestamp_ms BIGINT NOT NULL,
    screen TEXT,
    content_type TEXT,
    elapsed_ms BIGINT DEFAULT 0,
    extra_json TEXT
);

CREATE TABLE analytics_rollups_daily (
    day TEXT NOT NULL,
    event_type TEXT NOT NULL,
    screen TEXT NOT NULL DEFAULT '',
    content_type TEXT NOT NULL DEFAULT '',
    count BIGINT DEFAULT 0,
    total_elapsed_ms BIGINT DEFAULT 0,
    PRIMARY KEY (day, event_type, screen, content_type)
);

CREATE TABLE android_feed_retention (
    id BIGINT PRIMARY KEY CHECK (id = 1),
    feed_days BIGINT NOT NULL,
    reconciled_at_ms BIGINT NOT NULL
);

CREATE TABLE android_sync_clock (
    id BIGINT PRIMARY KEY CHECK (id = 1),
    epoch TEXT NOT NULL,
    revision BIGINT NOT NULL DEFAULT 0
);

CREATE TABLE android_sync_heads (
    owner_kind TEXT NOT NULL,
    owner_id TEXT NOT NULL,
    revision BIGINT NOT NULL,
    PRIMARY KEY (owner_kind, owner_id)
);

CREATE TABLE android_sync_health_reports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cursor TEXT NOT NULL,
    reported_at_ms BIGINT NOT NULL,
    payload_json TEXT NOT NULL,
    verified_assets BIGINT NOT NULL DEFAULT 0,
    pending_assets BIGINT NOT NULL DEFAULT 0,
    missing_assets BIGINT NOT NULL DEFAULT 0,
    total_assets BIGINT NOT NULL DEFAULT 0,
    verified_bytes BIGINT NOT NULL DEFAULT 0
);

CREATE TABLE auth_sessions (
    session_id TEXT UNIQUE,
    username TEXT NOT NULL,
    created_at_ms BIGINT NOT NULL,
    last_active_at_ms BIGINT NOT NULL,
    revoked BIGINT NOT NULL DEFAULT 0,
    revoke_reason TEXT
);

CREATE TABLE bookmark_categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    archive_path TEXT,
    created_at BIGINT NOT NULL DEFAULT 0
);

CREATE TABLE bookmarks (
    video_id TEXT UNIQUE,
    category_id BIGINT NOT NULL DEFAULT 0,
    custom_title TEXT,
    account_handles TEXT,
    media_indices TEXT,
    bookmarked_at BIGINT NOT NULL DEFAULT 0
);

CREATE TABLE category_create_receipts (
    request_id TEXT UNIQUE,
    category_id BIGINT NOT NULL,
    provisional_id TEXT NOT NULL,
    created_at_ms BIGINT NOT NULL
);

CREATE TABLE channel_follows (
    channel_id TEXT UNIQUE,
    followed_at BIGINT NOT NULL DEFAULT 0
);

CREATE TABLE channel_profiles (
    channel_id TEXT UNIQUE,
    platform TEXT NOT NULL,
    handle TEXT,
    display_name TEXT,
    bio TEXT,
    website TEXT,
    followers BIGINT DEFAULT 0,
    following BIGINT DEFAULT 0,
    verified BIGINT DEFAULT 0,
    verified_type TEXT,
    account_region TEXT,
    account_details_json TEXT,
    protected BIGINT DEFAULT 0,
    observed_at_ms BIGINT NOT NULL DEFAULT 0,
    fetched_at BIGINT NOT NULL DEFAULT 0,
    tombstone BIGINT DEFAULT 0
);

CREATE TABLE channel_settings (
    channel_id TEXT UNIQUE,
    media_only BIGINT,
    include_reposts BIGINT,
    media_download_limit BIGINT,
    max_videos BIGINT,
    download_subtitles BIGINT,
    include_member_only BIGINT,
    updated_at BIGINT NOT NULL DEFAULT 0
);

CREATE TABLE channel_stars (
    channel_id TEXT UNIQUE,
    starred_at BIGINT NOT NULL DEFAULT 0
);

CREATE TABLE channels (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    channel_id TEXT UNIQUE NOT NULL,
    source_id TEXT,
    name TEXT NOT NULL,
    url TEXT,
    platform TEXT,
    quality TEXT,
    last_checked BIGINT NOT NULL DEFAULT 0,
    created_at BIGINT NOT NULL DEFAULT 0
);

CREATE TABLE discover_generation (
    id BIGINT PRIMARY KEY CHECK(id = 1),
    candidates_json TEXT NOT NULL DEFAULT '[]',
    history_video_ids_json TEXT NOT NULL DEFAULT '[]',
    prepared_at_ms BIGINT NOT NULL DEFAULT 0,
    expires_at_ms BIGINT NOT NULL DEFAULT 0,
    refresh_started_at_ms BIGINT NOT NULL DEFAULT 0
);

CREATE TABLE download_queue (
    video_id TEXT UNIQUE,
    owner_channel_id TEXT NOT NULL,
    title TEXT NOT NULL DEFAULT '',
    published_at_ms BIGINT NOT NULL DEFAULT 0,
    status TEXT NOT NULL DEFAULT 'pending' CHECK(status IN ('pending', 'processing', 'blocked')),
    retry_count BIGINT NOT NULL DEFAULT 0,
    next_attempt_at_ms BIGINT NOT NULL DEFAULT 0,
    last_error_kind TEXT NOT NULL DEFAULT '',
    last_error TEXT NOT NULL DEFAULT '',
    lease_owner TEXT NOT NULL DEFAULT '',
    lease_until_ms BIGINT NOT NULL DEFAULT 0,
    added_at_ms BIGINT NOT NULL DEFAULT 0,
    started_at_ms BIGINT NOT NULL DEFAULT 0
);

CREATE TABLE downloader_operations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    operation TEXT NOT NULL,
    platform TEXT NOT NULL,
    subject TEXT NOT NULL DEFAULT '',
    tool TEXT NOT NULL,
    started_at_ms BIGINT NOT NULL,
    ended_at_ms BIGINT NOT NULL,
    status TEXT NOT NULL,
    error_kind TEXT NOT NULL DEFAULT '',
    error TEXT NOT NULL DEFAULT '',
    cookie_label TEXT NOT NULL DEFAULT '',
    elapsed_ms BIGINT NOT NULL DEFAULT 0,
    item_count BIGINT NOT NULL DEFAULT 0,
    media_count BIGINT NOT NULL DEFAULT 0,
    file_count BIGINT NOT NULL DEFAULT 0,
    bytes BIGINT NOT NULL DEFAULT 0,
    summary_json TEXT NOT NULL DEFAULT ''
);

CREATE TABLE feed_items (
    tweet_id TEXT UNIQUE,
    source_channel_id TEXT,
    channel_id TEXT,
    body_text TEXT,
    article_title TEXT,
    poll_json TEXT,
    community_note TEXT,
    lang TEXT,
    is_retweet BIGINT DEFAULT 0,
    quote_tweet_id TEXT,
    quote_channel_id TEXT,
    quote_body_text TEXT,
    quote_article_title TEXT,
    quote_poll_json TEXT,
    quote_community_note TEXT,
    quote_lang TEXT,
    quote_media_json TEXT,
    media_json TEXT,
    canonical_url TEXT,
    reply_channel_id TEXT,
    reply_to_status TEXT,
    reposter_channel_id TEXT,
    is_reply BIGINT DEFAULT 0,
    is_ghost BIGINT DEFAULT 0,
    quote_published_at BIGINT NOT NULL DEFAULT 0,
    views BIGINT,
    likes BIGINT,
    retweets BIGINT,
    published_at BIGINT NOT NULL DEFAULT 0,
    fetched_at BIGINT NOT NULL DEFAULT 0,
    content_hash TEXT,
    canonical_tweet_id TEXT,
    algo_interest DOUBLE PRECISION DEFAULT 0,
    algo_scored_at BIGINT DEFAULT 0,
    ingest_order BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE
);

CREATE TABLE feed_likes (
    tweet_id TEXT UNIQUE,
    liked_at BIGINT NOT NULL DEFAULT 0
);

CREATE TABLE feed_order_invalidations (
    owner_kind TEXT NOT NULL CHECK (owner_kind IN ('tweet', 'channel')),
    owner_id TEXT NOT NULL CHECK (TRIM(owner_id) != ''),
    PRIMARY KEY (owner_kind, owner_id)
);

CREATE TABLE feed_rank_snapshot (
    tweet_id TEXT UNIQUE,
    rank_position BIGINT NOT NULL,
    base_score DOUBLE PRECISION NOT NULL,
    decay_factor DOUBLE PRECISION NOT NULL,
    freshness_bonus DOUBLE PRECISION NOT NULL,
    jitter DOUBLE PRECISION NOT NULL,
    diversity_demoted_by DOUBLE PRECISION NOT NULL DEFAULT 0,
    final_score DOUBLE PRECISION NOT NULL,
    computed_at BIGINT NOT NULL
);

CREATE TABLE feed_rank_snapshot_history (
    computed_at BIGINT NOT NULL,
    tweet_id TEXT NOT NULL,
    rank_position BIGINT NOT NULL,
    base_score DOUBLE PRECISION NOT NULL,
    decay_factor DOUBLE PRECISION NOT NULL,
    freshness_bonus DOUBLE PRECISION NOT NULL,
    jitter DOUBLE PRECISION NOT NULL,
    diversity_demoted_by DOUBLE PRECISION NOT NULL DEFAULT 0,
    final_score DOUBLE PRECISION NOT NULL,
    PRIMARY KEY (computed_at, tweet_id),
    UNIQUE (computed_at, rank_position)
);

CREATE TABLE feed_seen (
    tweet_id TEXT UNIQUE,
    seen_at BIGINT NOT NULL DEFAULT 0
);

CREATE TABLE feed_share_account_affinity (
    handle TEXT UNIQUE,
    score DOUBLE PRECISION DEFAULT 0,
    last_event_at_ms BIGINT,
    event_count BIGINT DEFAULT 0
);

CREATE TABLE feed_share_token_affinity (
    token TEXT UNIQUE,
    score DOUBLE PRECISION DEFAULT 0,
    last_event_at_ms BIGINT,
    event_count BIGINT DEFAULT 0
);

CREATE TABLE feed_sources (
    source_id TEXT UNIQUE,
    platform TEXT NOT NULL,
    source_type TEXT NOT NULL,
    external_id TEXT NOT NULL,
    label TEXT NOT NULL,
    url TEXT NOT NULL,
    enabled BIGINT NOT NULL DEFAULT 1,
    last_checked BIGINT,
    last_ok BIGINT,
    last_error TEXT NOT NULL DEFAULT '',
    created_at BIGINT NOT NULL DEFAULT 0,
    updated_at BIGINT NOT NULL DEFAULT 0
);

CREATE TABLE home_layouts (
    username TEXT PRIMARY KEY,
    layout_json TEXT NOT NULL,
    updated_at_ms BIGINT NOT NULL
);

CREATE TABLE ingest_state (
    handle TEXT UNIQUE,
    fail_count BIGINT DEFAULT 0,
    next_retry_at DOUBLE PRECISION,
    last_success_at DOUBLE PRECISION,
    last_attempt_at DOUBLE PRECISION,
    last_error TEXT,
    last_http_status BIGINT,
    avg_latency_ms DOUBLE PRECISION,
    updated_at BIGINT NOT NULL DEFAULT 0
);

CREATE TABLE media_objects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    object_id TEXT UNIQUE NOT NULL,
    object_key TEXT UNIQUE NOT NULL,
    source_url TEXT NOT NULL DEFAULT '',
    published_source_url TEXT NOT NULL DEFAULT '',
    storage_class TEXT NOT NULL CHECK(storage_class IN ('state_ssd', 'bulk_hdd')),
    download_lane TEXT NOT NULL DEFAULT 'backfill' CHECK(download_lane IN ('current', 'backfill')),
    desired_revision BIGINT NOT NULL DEFAULT 1,
    published_revision BIGINT NOT NULL DEFAULT 0,
    file_path TEXT NOT NULL DEFAULT '',
    content_type TEXT NOT NULL DEFAULT '',
    size_bytes BIGINT NOT NULL DEFAULT 0,
    file_mtime_ns BIGINT NOT NULL DEFAULT 0,
    job_state TEXT NOT NULL DEFAULT 'queued',
    last_error_kind TEXT NOT NULL DEFAULT '',
    last_error TEXT NOT NULL DEFAULT '',
    attempts BIGINT NOT NULL DEFAULT 0,
    next_attempt_at_ms BIGINT NOT NULL DEFAULT 0,
    lease_owner TEXT NOT NULL DEFAULT '',
    lease_until_ms BIGINT NOT NULL DEFAULT 0,
    created_at_ms BIGINT NOT NULL DEFAULT 0,
    updated_at_ms BIGINT NOT NULL DEFAULT 0
);

CREATE TABLE moment_views (
    video_id TEXT UNIQUE,
    viewed_at BIGINT NOT NULL DEFAULT 0
);

CREATE TABLE moments_cursors (
    scope TEXT UNIQUE CHECK (scope IN ('all', 'following', 'stories')),
    video_id TEXT NOT NULL,
    position_ms BIGINT NOT NULL DEFAULT 0,
    sort_at_ms BIGINT NOT NULL DEFAULT 0,
    order_position BIGINT NOT NULL DEFAULT 0,
    updated_at_ms BIGINT NOT NULL DEFAULT 0
);

CREATE TABLE moments_order_counters (
    scope TEXT PRIMARY KEY CHECK (scope IN ('all', 'following')),
    next_position BIGINT NOT NULL DEFAULT 1
);

CREATE TABLE moments_order_history (
    scope TEXT NOT NULL CHECK (scope IN ('all', 'following')),
    video_id TEXT NOT NULL,
    order_position BIGINT NOT NULL CHECK (order_position > 0),
    PRIMARY KEY (scope, video_id)
);

CREATE TABLE mutation_clocks (
    kind TEXT NOT NULL CHECK (kind IN ('like', 'bookmark', 'follow', 'star', 'mute', 'progress')),
    item_key TEXT NOT NULL,
    action TEXT NOT NULL CHECK (action IN ('set', 'clear')),
    updated_at_ms BIGINT NOT NULL,
    PRIMARY KEY (kind, item_key)
);

CREATE TABLE muted_channels (
    channel_id TEXT UNIQUE,
    muted_at BIGINT NOT NULL DEFAULT 0
);

CREATE TABLE retweet_sources (
    content_hash TEXT NOT NULL,
    retweeter_channel_id TEXT NOT NULL,
    tweet_id TEXT NOT NULL,
    published_at BIGINT NOT NULL DEFAULT 0,
    PRIMARY KEY (content_hash, retweeter_channel_id)
);

CREATE TABLE schema_migrations (
    name TEXT PRIMARY KEY,
    applied_at_ms BIGINT NOT NULL
);

CREATE TABLE settings (
    key TEXT NOT NULL,
    value TEXT,
    PRIMARY KEY (key)
);

CREATE TABLE sponsorblock_checked (
    video_id TEXT UNIQUE,
    checked_at BIGINT NOT NULL DEFAULT 0,
    video_age_at_check TEXT
);

CREATE TABLE sponsorblock_segments (
    video_id TEXT NOT NULL,
    start_time DOUBLE PRECISION NOT NULL,
    end_time DOUBLE PRECISION NOT NULL,
    category TEXT NOT NULL,
    PRIMARY KEY (video_id, start_time)
);

CREATE TABLE temp_download_queue (
    url TEXT UNIQUE,
    request_id TEXT NOT NULL DEFAULT '',
    save_intent_json TEXT NOT NULL DEFAULT '',
    platform TEXT NOT NULL,
    origin TEXT NOT NULL DEFAULT 'interactive' CHECK(origin IN ('interactive', 'discover')),
    status TEXT NOT NULL DEFAULT 'pending' CHECK(status IN ('pending', 'processing', 'blocked')),
    retry_count BIGINT NOT NULL DEFAULT 0,
    next_attempt_at_ms BIGINT NOT NULL DEFAULT 0,
    last_error_kind TEXT NOT NULL DEFAULT '',
    last_error TEXT NOT NULL DEFAULT '',
    lease_owner TEXT NOT NULL DEFAULT '',
    lease_until_ms BIGINT NOT NULL DEFAULT 0,
    added_at_ms BIGINT NOT NULL DEFAULT 0,
    started_at_ms BIGINT NOT NULL DEFAULT 0
);

CREATE TABLE translation_jobs (
    tweet_id TEXT NOT NULL,
    field TEXT NOT NULL,
    target_lang TEXT NOT NULL,
    source_hash TEXT NOT NULL DEFAULT '',
    status TEXT NOT NULL DEFAULT 'queued',
    priority BIGINT NOT NULL DEFAULT 0,
    attempts BIGINT NOT NULL DEFAULT 0,
    next_attempt_at BIGINT NOT NULL DEFAULT 0,
    last_error_kind TEXT NOT NULL DEFAULT '',
    last_error TEXT NOT NULL DEFAULT '',
    created_at BIGINT NOT NULL DEFAULT 0,
    updated_at BIGINT NOT NULL DEFAULT 0,
    PRIMARY KEY (tweet_id, field, target_lang)
);

CREATE TABLE translations (
    tweet_id TEXT NOT NULL,
    field TEXT NOT NULL,
    source_lang TEXT NOT NULL,
    target_lang TEXT NOT NULL,
    translated_text TEXT NOT NULL,
    translated_at BIGINT NOT NULL DEFAULT 0,
    PRIMARY KEY (tweet_id, field, target_lang)
);

CREATE TABLE video_comments (
    video_id TEXT NOT NULL,
    comment_id TEXT NOT NULL,
    parent_id TEXT,
    author_name TEXT,
    author_id TEXT,
    text TEXT,
    like_count BIGINT,
    published_at BIGINT NOT NULL DEFAULT 0,
    PRIMARY KEY(video_id, comment_id)
);

CREATE TABLE video_desires (
    source_channel_id TEXT NOT NULL,
    source_component TEXT NOT NULL,
    video_id TEXT NOT NULL,
    source_position BIGINT NOT NULL DEFAULT 0,
    lane TEXT NOT NULL CHECK(lane IN ('current', 'backfill')),
    PRIMARY KEY (source_channel_id, source_component, video_id)
);

CREATE TABLE video_fetch_history (
    video_id TEXT PRIMARY KEY,
    fetched_at_ms BIGINT NOT NULL DEFAULT 0
);

CREATE TABLE video_repost_sources (
    video_id TEXT NOT NULL,
    reposter_channel_id TEXT NOT NULL,
    reposted_at_ms BIGINT NOT NULL DEFAULT 0,
    first_seen_at_ms BIGINT NOT NULL DEFAULT 0,
    updated_at_ms BIGINT NOT NULL DEFAULT 0,
    PRIMARY KEY (video_id, reposter_channel_id)
);

CREATE TABLE videos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    video_id TEXT UNIQUE NOT NULL,
    channel_id TEXT NOT NULL,
    owner_kind TEXT NOT NULL CHECK(owner_kind IN ('tweet', 'youtube_video', 'instagram_reel', 'tiktok_video')),
    title TEXT,
    description TEXT,
    duration BIGINT,
    published_at BIGINT NOT NULL DEFAULT 0,
    downloaded_at BIGINT NOT NULL DEFAULT 0,
    is_temp BIGINT DEFAULT 0,
    is_pinned BIGINT DEFAULT 0,
    metadata_json TEXT,
    media_kind TEXT DEFAULT '',
    slide_count BIGINT DEFAULT 0,
    source_kind TEXT DEFAULT '',
    dearrow_title TEXT,
    dearrow_title_casual TEXT,
    dearrow_checked_at BIGINT,
    moments_all_position BIGINT NOT NULL DEFAULT 0,
    moments_following_position BIGINT NOT NULL DEFAULT 0
);

CREATE TABLE watch_history (
    video_id TEXT UNIQUE,
    playback_position DOUBLE PRECISION NOT NULL DEFAULT 0,
    duration DOUBLE PRECISION,
    updated_at_ms BIGINT NOT NULL DEFAULT 0
);

CREATE TABLE youtube_broadcasts (
    channel_id TEXT NOT NULL,
    video_id TEXT NOT NULL,
    title TEXT NOT NULL DEFAULT '',
    thumbnail_url TEXT NOT NULL DEFAULT '',
    live_status TEXT NOT NULL DEFAULT '',
    published_at_ms BIGINT NOT NULL DEFAULT 0,
    starts_at_ms BIGINT NOT NULL DEFAULT 0,
    concurrent_view_count BIGINT,
    observed_at_ms BIGINT NOT NULL,
    source_rank BIGINT NOT NULL DEFAULT 0,
    PRIMARY KEY (channel_id, video_id)
);

CREATE TABLE assets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asset_id TEXT UNIQUE NOT NULL,
    asset_kind TEXT NOT NULL,
    owner_kind TEXT NOT NULL,
    owner_id TEXT NOT NULL,
    media_index BIGINT NOT NULL DEFAULT 0,
    object_id TEXT NOT NULL,
    desired_object_id TEXT NOT NULL,
    lifecycle_state TEXT NOT NULL DEFAULT 'active' CHECK(lifecycle_state IN ('active', 'pruned')),
    revision BIGINT NOT NULL DEFAULT 1,
    is_auto BIGINT,
    audio_language TEXT NOT NULL DEFAULT '',
    required_reason TEXT NOT NULL DEFAULT '',
    created_at_ms BIGINT NOT NULL DEFAULT 0,
    updated_at_ms BIGINT NOT NULL DEFAULT 0,
    FOREIGN KEY (object_id) REFERENCES media_objects(object_id),
    FOREIGN KEY (desired_object_id) REFERENCES media_objects(object_id),
    UNIQUE(asset_kind, owner_kind, owner_id, media_index)
);

CREATE TABLE auth_refresh_tokens (
    token_id TEXT UNIQUE,
    session_id TEXT NOT NULL,
    issued_at_ms BIGINT NOT NULL,
    expires_at_ms BIGINT NOT NULL,
    consumed_at_ms BIGINT,
    FOREIGN KEY (session_id) REFERENCES auth_sessions(session_id) ON DELETE CASCADE
);

CREATE TABLE discover_refresh_anchors (
    anchor_video_id TEXT PRIMARY KEY,
    FOREIGN KEY (anchor_video_id) REFERENCES videos(video_id) ON DELETE CASCADE
);

CREATE TABLE discover_temp_downloads (
    video_id TEXT PRIMARY KEY,
    downloaded_at_ms BIGINT NOT NULL DEFAULT 0,
    FOREIGN KEY (video_id) REFERENCES videos(video_id) ON DELETE CASCADE
);

CREATE TABLE feed_item_sources (
    tweet_id TEXT NOT NULL,
    source_id TEXT NOT NULL,
    first_seen_at BIGINT NOT NULL DEFAULT 0,
    last_seen_at BIGINT NOT NULL DEFAULT 0,
    PRIMARY KEY (tweet_id, source_id),
    FOREIGN KEY (source_id) REFERENCES feed_sources(source_id) ON DELETE CASCADE
);

CREATE TABLE profile_jobs (
    channel_id TEXT UNIQUE,
    requested_revision BIGINT NOT NULL DEFAULT 1,
    completed_revision BIGINT NOT NULL DEFAULT 0,
    requested_at_ms BIGINT NOT NULL DEFAULT 0,
    lease_owner TEXT NOT NULL DEFAULT '',
    lease_until_ms BIGINT NOT NULL DEFAULT 0,
    attempts BIGINT NOT NULL DEFAULT 0,
    next_attempt_at_ms BIGINT NOT NULL DEFAULT 0,
    last_error TEXT NOT NULL DEFAULT '',
    updated_at_ms BIGINT NOT NULL DEFAULT 0,
    FOREIGN KEY (channel_id) REFERENCES channel_profiles(channel_id) ON DELETE CASCADE
);

CREATE TABLE video_metadata_jobs (
    video_id TEXT UNIQUE,
    status TEXT NOT NULL DEFAULT 'pending' CHECK(status IN ('pending', 'processing', 'done', 'blocked')),
    checked_at_ms BIGINT NOT NULL DEFAULT 0,
    video_age_at_check TEXT NOT NULL DEFAULT '',
    attempts BIGINT NOT NULL DEFAULT 0,
    next_attempt_at_ms BIGINT NOT NULL DEFAULT 0,
    last_error TEXT NOT NULL DEFAULT '',
    lease_owner TEXT NOT NULL DEFAULT '',
    lease_until_ms BIGINT NOT NULL DEFAULT 0,
    requested_at_ms BIGINT NOT NULL DEFAULT 0,
    updated_at_ms BIGINT NOT NULL DEFAULT 0,
    FOREIGN KEY (video_id) REFERENCES videos(video_id) ON DELETE CASCADE
);

CREATE TABLE web_video_streams (
    video_id TEXT PRIMARY KEY REFERENCES videos(video_id) ON DELETE CASCADE,
    observed_at_ms BIGINT NOT NULL
);

CREATE TABLE youtube_recommendations (
    anchor_video_id TEXT UNIQUE,
    candidates_json TEXT NOT NULL DEFAULT '[]',
    status TEXT NOT NULL DEFAULT 'pending' CHECK(status IN ('pending', 'processing', 'ready', 'blocked')),
    fetched_at_ms BIGINT NOT NULL DEFAULT 0,
    expires_at_ms BIGINT NOT NULL DEFAULT 0,
    attempts BIGINT NOT NULL DEFAULT 0,
    next_attempt_at_ms BIGINT NOT NULL DEFAULT 0,
    last_error TEXT NOT NULL DEFAULT '',
    lease_owner TEXT NOT NULL DEFAULT '',
    lease_until_ms BIGINT NOT NULL DEFAULT 0,
    requested_at_ms BIGINT NOT NULL DEFAULT 0,
    updated_at_ms BIGINT NOT NULL DEFAULT 0,
    FOREIGN KEY (anchor_video_id) REFERENCES videos(video_id) ON DELETE CASCADE
);

CREATE UNIQUE INDEX idx_android_sync_heads_revision ON android_sync_heads(revision);

CREATE INDEX idx_android_sync_health_cursor ON android_sync_health_reports(cursor, reported_at_ms DESC);

CREATE INDEX idx_android_sync_health_reported ON android_sync_health_reports(reported_at_ms DESC, id DESC);

CREATE INDEX idx_assets_desired_object ON assets(desired_object_id);

CREATE INDEX idx_assets_object ON assets(object_id);

CREATE INDEX idx_assets_owner ON assets(owner_kind, owner_id, asset_kind, media_index);

CREATE INDEX idx_auth_refresh_session ON auth_refresh_tokens(session_id);

CREATE INDEX idx_auth_sessions_user ON auth_sessions(username, revoked);

CREATE INDEX idx_bookmarks_date ON bookmarks(bookmarked_at DESC);

CREATE INDEX idx_channel_profiles_platform ON channel_profiles(platform);

CREATE INDEX idx_channel_profiles_refresh ON channel_profiles(tombstone, fetched_at) WHERE tombstone = 0;

CREATE INDEX idx_channel_profiles_twitter_handle ON channel_profiles(LOWER(COALESCE(handle, ''))) WHERE platform = 'twitter' AND tombstone = 0;

CREATE INDEX idx_channels_platform ON channels(platform);

CREATE INDEX idx_download_queue_lease ON download_queue(status, lease_until_ms);

CREATE INDEX idx_download_queue_ready ON download_queue(status, next_attempt_at_ms, lease_until_ms, added_at_ms);

CREATE INDEX idx_downloader_operations_recent ON downloader_operations(started_at_ms DESC, id DESC);

CREATE INDEX idx_downloader_operations_summary ON downloader_operations(platform, operation, status, error_kind);

CREATE INDEX idx_feed_item_sources_source ON feed_item_sources(source_id, last_seen_at DESC);

CREATE INDEX idx_feed_items_algo ON feed_items(algo_interest DESC, published_at DESC);

CREATE INDEX idx_feed_items_author_fetched ON feed_items(channel_id, fetched_at DESC, published_at DESC, tweet_id DESC) WHERE channel_id IS NOT NULL AND channel_id != '';

CREATE INDEX idx_feed_items_canonical_tweet ON feed_items(canonical_tweet_id) WHERE canonical_tweet_id IS NOT NULL AND canonical_tweet_id != '';

CREATE INDEX idx_feed_items_channel ON feed_items(channel_id, published_at DESC);

CREATE INDEX idx_feed_items_content_hash ON feed_items(content_hash) WHERE content_hash IS NOT NULL AND content_hash != '';

CREATE INDEX idx_feed_items_fetched ON feed_items(fetched_at DESC, tweet_id DESC);

CREATE INDEX idx_feed_items_media_author ON feed_items(channel_id, published_at DESC) WHERE media_json IS NOT NULL AND media_json != '' AND media_json != '[]' AND is_retweet = 0;

CREATE INDEX idx_feed_items_published ON feed_items(published_at DESC, tweet_id DESC);

CREATE INDEX idx_feed_items_quote ON feed_items(quote_tweet_id) WHERE quote_tweet_id IS NOT NULL AND quote_tweet_id != '';

CREATE INDEX idx_feed_items_quote_channel ON feed_items(quote_channel_id, published_at DESC) WHERE quote_channel_id IS NOT NULL AND quote_channel_id != '';

CREATE INDEX idx_feed_items_reply_channel ON feed_items(reply_channel_id, published_at DESC) WHERE reply_channel_id IS NOT NULL AND reply_channel_id != '';

CREATE INDEX idx_feed_items_reply_parent ON feed_items(reply_to_status, published_at, tweet_id) WHERE reply_to_status IS NOT NULL AND reply_to_status != '';

CREATE INDEX idx_feed_items_reposter_channel ON feed_items(reposter_channel_id, published_at DESC) WHERE reposter_channel_id IS NOT NULL AND reposter_channel_id != '';

CREATE INDEX idx_feed_items_seen_cover ON feed_items(tweet_id, quote_tweet_id, canonical_tweet_id, channel_id, source_channel_id, is_ghost);

CREATE INDEX idx_feed_items_source_channel ON feed_items(source_channel_id, ingest_order DESC);

CREATE INDEX idx_feed_items_unscored ON feed_items(ingest_order DESC) WHERE algo_scored_at = 0;

CREATE INDEX idx_feed_rank_snapshot_at ON feed_rank_snapshot(computed_at);

CREATE INDEX idx_feed_rank_snapshot_history_tweet ON feed_rank_snapshot_history(tweet_id, computed_at);

CREATE INDEX idx_feed_rank_snapshot_pos ON feed_rank_snapshot(rank_position);

CREATE INDEX idx_feed_rank_snapshot_score ON feed_rank_snapshot(final_score DESC);

CREATE INDEX idx_feed_seen_at ON feed_seen(seen_at, tweet_id);

CREATE INDEX idx_feed_sources_platform ON feed_sources(platform, enabled);

CREATE INDEX idx_media_objects_claim ON media_objects(download_lane, next_attempt_at_ms, attempts, updated_at_ms DESC, id DESC, lease_until_ms) WHERE job_state IN ('queued', 'downloading') AND (source_url != '' OR object_key LIKE 'derived:video-thumbnail:%');

CREATE INDEX idx_media_objects_lease ON media_objects(download_lane, lease_until_ms) WHERE job_state = 'downloading' AND (source_url != '' OR object_key LIKE 'derived:video-thumbnail:%');

CREATE INDEX idx_media_objects_ready_file_path ON media_objects(file_path) WHERE published_revision > 0;

CREATE INDEX idx_moment_views_date ON moment_views(viewed_at DESC);

CREATE INDEX idx_profile_jobs_claim ON profile_jobs(requested_at_ms DESC, channel_id, next_attempt_at_ms, lease_until_ms, lease_owner) WHERE requested_revision > completed_revision;

CREATE INDEX idx_retweet_sources_actor_hash ON retweet_sources(retweeter_channel_id, content_hash);

CREATE INDEX idx_retweet_sources_published ON retweet_sources(published_at, content_hash);

CREATE INDEX idx_temp_download_queue_ready ON temp_download_queue(origin, status, next_attempt_at_ms, lease_until_ms, added_at_ms);

CREATE INDEX idx_translation_jobs_ready ON translation_jobs(target_lang, status, priority DESC, updated_at, tweet_id, field, next_attempt_at);

CREATE INDEX idx_video_comments_video_likes ON video_comments(video_id, COALESCE(like_count, 0) DESC, comment_id ASC);

CREATE INDEX idx_video_desires_source_position ON video_desires(source_channel_id, source_component, source_position, video_id);

CREATE INDEX idx_video_desires_video ON video_desires(video_id, lane, source_position);

CREATE INDEX idx_video_metadata_jobs_ready ON video_metadata_jobs(status, next_attempt_at_ms, lease_until_ms, requested_at_ms);

CREATE INDEX idx_video_repost_sources_reposter ON video_repost_sources(reposter_channel_id);

CREATE INDEX idx_video_repost_sources_time ON video_repost_sources(reposted_at_ms DESC, first_seen_at_ms DESC);

CREATE INDEX idx_video_repost_sources_video ON video_repost_sources(video_id);

CREATE INDEX idx_videos_channel_published ON videos(channel_id, published_at DESC);

CREATE INDEX idx_videos_media_shape ON videos(media_kind, slide_count);

CREATE INDEX idx_videos_moments_all_unpositioned ON videos(channel_id, video_id) WHERE moments_all_position = 0;

CREATE INDEX idx_videos_moments_following_unpositioned ON videos(channel_id, video_id) WHERE moments_following_position = 0;

CREATE INDEX idx_videos_source_kind ON videos(source_kind, published_at DESC);

CREATE INDEX idx_youtube_recommendations_fetched ON youtube_recommendations(fetched_at_ms DESC, anchor_video_id);

CREATE INDEX idx_youtube_recommendations_ready ON youtube_recommendations(status, next_attempt_at_ms, lease_until_ms, requested_at_ms);

CREATE VIEW feed_items_resolved AS SELECT fi.*, COALESCE(source_profile.handle, '') AS source_handle, COALESCE(author_profile.handle, '') AS author_handle, COALESCE(author_profile.display_name, '') AS author_display_name, CASE WHEN COALESCE(fi.channel_id, '') = '' THEN '' ELSE '/api/media/avatar/' || fi.channel_id END AS author_avatar_url, COALESCE(reposter_profile.handle, '') AS retweeted_by_handle, COALESCE(reposter_profile.display_name, '') AS retweeted_by_display_name, COALESCE(quote_profile.display_name, '') AS quote_author_display_name, COALESCE(quote_profile.handle, '') AS quote_author_handle, CASE WHEN COALESCE(fi.quote_channel_id, '') = '' THEN '' ELSE '/api/media/avatar/' || fi.quote_channel_id END AS quote_author_avatar_url, COALESCE(reply_profile.handle, '') AS reply_to_handle FROM feed_items fi LEFT JOIN channel_profiles source_profile ON source_profile.channel_id = fi.source_channel_id AND source_profile.tombstone = 0 LEFT JOIN channel_profiles author_profile ON author_profile.channel_id = fi.channel_id AND author_profile.tombstone = 0 LEFT JOIN channel_profiles reposter_profile ON reposter_profile.channel_id = fi.reposter_channel_id AND reposter_profile.tombstone = 0 LEFT JOIN channel_profiles quote_profile ON quote_profile.channel_id = fi.quote_channel_id AND quote_profile.tombstone = 0 LEFT JOIN channel_profiles reply_profile ON reply_profile.channel_id = fi.reply_channel_id AND reply_profile.tombstone = 0;

CREATE VIEW retweet_sources_resolved AS SELECT rs.content_hash, rs.retweeter_channel_id, COALESCE(cp.handle, '') AS retweeter_handle, cp.display_name AS retweeter_display_name, rs.tweet_id, rs.published_at FROM retweet_sources rs LEFT JOIN channel_profiles cp ON cp.channel_id = rs.retweeter_channel_id AND cp.tombstone = 0;

CREATE VIEW video_repost_sources_resolved AS SELECT vrs.video_id, vrs.reposter_channel_id, COALESCE(cp.handle, '') AS reposter_handle, cp.display_name AS reposter_display_name, vrs.reposted_at_ms, vrs.first_seen_at_ms, vrs.updated_at_ms FROM video_repost_sources vrs LEFT JOIN channel_profiles cp ON cp.channel_id = vrs.reposter_channel_id AND cp.tombstone = 0;

INSERT INTO android_sync_clock (id, epoch, revision) VALUES (1, replace(gen_random_uuid()::TEXT, '-', ''), 0);

-- +goose StatementBegin
CREATE FUNCTION igloo_sync_touch_head(kind TEXT, owner TEXT) RETURNS VOID
LANGUAGE plpgsql AS $$
DECLARE
    next_revision BIGINT;
BEGIN
    UPDATE android_sync_clock SET revision = revision + 1 WHERE id = 1
    RETURNING revision INTO next_revision;
    INSERT INTO android_sync_heads (owner_kind, owner_id, revision)
    VALUES (kind, owner, next_revision)
    ON CONFLICT (owner_kind, owner_id) DO UPDATE SET revision = EXCLUDED.revision;
END;
$$;
-- +goose StatementEnd

-- +goose StatementBegin
CREATE FUNCTION igloo_sync_owner_head() RETURNS TRIGGER
LANGUAGE plpgsql AS $$
DECLARE
    old_row JSONB;
    new_row JSONB;
    old_owner TEXT;
    new_owner TEXT;
BEGIN
    IF TG_OP = 'DELETE' THEN
        old_owner := to_jsonb(OLD) ->> TG_ARGV[1];
        IF trim(old_owner) <> '' THEN
            PERFORM igloo_sync_touch_head(TG_ARGV[0], old_owner);
        END IF;
        RETURN OLD;
    END IF;

    new_row := to_jsonb(NEW);
    new_owner := new_row ->> TG_ARGV[1];
    IF trim(new_owner) <> '' THEN
        IF TG_OP = 'UPDATE' THEN
            old_row := to_jsonb(OLD);
            IF NOT EXISTS (
                SELECT 1 FROM unnest(string_to_array(TG_ARGV[2], ',')) column_name
                WHERE old_row -> column_name IS DISTINCT FROM new_row -> column_name
            ) THEN
                RETURN NEW;
            END IF;
            old_owner := old_row ->> TG_ARGV[1];
            IF old_owner IS DISTINCT FROM new_owner THEN
                UPDATE android_sync_clock SET revision = revision + 1 WHERE id = 1;
                IF trim(old_owner) <> '' THEN
                    INSERT INTO android_sync_heads (owner_kind, owner_id, revision)
                    SELECT TG_ARGV[0], old_owner, revision FROM android_sync_clock WHERE id = 1
                    ON CONFLICT (owner_kind, owner_id) DO UPDATE SET revision = EXCLUDED.revision;
                END IF;
            END IF;
        END IF;
        PERFORM igloo_sync_touch_head(TG_ARGV[0], new_owner);
    END IF;
    RETURN NEW;
END;
$$;
-- +goose StatementEnd

-- +goose StatementBegin
CREATE FUNCTION igloo_sync_touch_feed_peers(hash TEXT) RETURNS VOID
LANGUAGE SQL AS $$
    WITH peers AS MATERIALIZED (
        SELECT tweet_id,
               row_number() OVER (ORDER BY tweet_id COLLATE "C") AS position,
               count(*) OVER () AS peer_count
        FROM feed_items
        WHERE content_hash IS NOT NULL AND content_hash <> '' AND content_hash = hash
    ), clock AS (
        UPDATE android_sync_clock SET revision = revision + (SELECT count(*) FROM peers) WHERE id = 1
        RETURNING revision
    )
    INSERT INTO android_sync_heads (owner_kind, owner_id, revision)
    SELECT 'feed', peers.tweet_id, clock.revision - peers.peer_count + peers.position
    FROM peers CROSS JOIN clock
    ON CONFLICT (owner_kind, owner_id) DO UPDATE SET revision = EXCLUDED.revision;
$$;
-- +goose StatementEnd

-- +goose StatementBegin
CREATE FUNCTION igloo_sync_feed_peers() RETURNS TRIGGER
LANGUAGE plpgsql AS $$
DECLARE
    old_row JSONB;
    new_row JSONB;
    old_hash TEXT;
    new_hash TEXT;
    old_target TEXT;
    new_target TEXT;
    touch_old BOOLEAN;
    touch_new BOOLEAN;
BEGIN
    IF TG_OP <> 'INSERT' THEN old_row := to_jsonb(OLD); END IF;
    IF TG_OP <> 'DELETE' THEN new_row := to_jsonb(NEW); END IF;
    old_target := old_row ->> TG_ARGV[0];
    new_target := new_row ->> TG_ARGV[0];
    touch_old := (TG_OP = 'DELETE' OR (TG_OP = 'UPDATE' AND old_target IS DISTINCT FROM new_target))
        AND coalesce(old_target, '') <> '';
    touch_new := (TG_OP = 'INSERT' OR (TG_OP = 'UPDATE' AND EXISTS (
        SELECT 1 FROM unnest(string_to_array(TG_ARGV[2], ',')) column_name
        WHERE old_row -> column_name IS DISTINCT FROM new_row -> column_name
    ))) AND coalesce(new_target, '') <> '';
    IF NOT touch_old AND NOT touch_new THEN RETURN NULL; END IF;
    PERFORM 1 FROM android_sync_clock WHERE id = 1 FOR UPDATE;
    IF TG_ARGV[1] = 'lookup' THEN
        SELECT content_hash INTO old_hash FROM feed_items WHERE tweet_id = old_target;
        SELECT content_hash INTO new_hash FROM feed_items WHERE tweet_id = new_target;
    ELSE
        old_hash := old_target;
        new_hash := new_target;
    END IF;
    IF touch_old AND coalesce(old_hash, '') <> '' THEN
        PERFORM igloo_sync_touch_feed_peers(old_hash);
    END IF;
    IF touch_new AND coalesce(new_hash, '') <> '' THEN
        PERFORM igloo_sync_touch_feed_peers(new_hash);
    END IF;
    RETURN NULL;
END;
$$;
-- +goose StatementEnd

-- +goose StatementBegin
CREATE FUNCTION igloo_sync_feed_old_edges() RETURNS TRIGGER
LANGUAGE plpgsql AS $$
DECLARE
    old_row JSONB := to_jsonb(OLD);
    new_row JSONB;
    column_name TEXT;
    owner TEXT;
BEGIN
    IF TG_OP = 'UPDATE' THEN new_row := to_jsonb(NEW); END IF;
    FOREACH column_name IN ARRAY ARRAY['quote_tweet_id', 'reply_to_status'] LOOP
        owner := old_row ->> column_name;
        IF coalesce(owner, '') <> ''
           AND (TG_OP = 'DELETE' OR old_row -> column_name IS DISTINCT FROM new_row -> column_name) THEN
            PERFORM 1 FROM android_sync_clock WHERE id = 1 FOR UPDATE;
            IF EXISTS (SELECT 1 FROM feed_items WHERE tweet_id = owner) THEN
                PERFORM igloo_sync_touch_head('feed', owner);
            END IF;
        END IF;
    END LOOP;
    RETURN NULL;
END;
$$;
-- +goose StatementEnd

-- +goose StatementBegin
CREATE FUNCTION igloo_sync_protected_heads() RETURNS TRIGGER
LANGUAGE plpgsql AS $$
DECLARE
    old_owner TEXT;
    new_owner TEXT;
BEGIN
    IF TG_OP <> 'INSERT' THEN old_owner := to_jsonb(OLD) ->> TG_ARGV[0]; END IF;
    IF TG_OP <> 'DELETE' THEN new_owner := to_jsonb(NEW) ->> TG_ARGV[0]; END IF;
    IF TG_OP = 'DELETE' OR (TG_OP = 'UPDATE' AND old_owner IS DISTINCT FROM new_owner) THEN
        IF trim(old_owner) <> '' THEN
            PERFORM igloo_sync_touch_head('feed', old_owner);
            PERFORM igloo_sync_touch_head('video', old_owner);
        END IF;
    END IF;
    IF TG_OP = 'INSERT' OR (TG_OP = 'UPDATE' AND old_owner IS DISTINCT FROM new_owner) THEN
        IF trim(new_owner) <> '' THEN
            PERFORM igloo_sync_touch_head('feed', new_owner);
            PERFORM igloo_sync_touch_head('video', new_owner);
        END IF;
    END IF;
    RETURN NULL;
END;
$$;
-- +goose StatementEnd

-- +goose StatementBegin
CREATE FUNCTION igloo_sync_setting_heads() RETURNS TRIGGER
LANGUAGE plpgsql AS $$
DECLARE
    relevant TEXT[] := ARRAY['moments_include_reposts_default', 'instagram_include_tagged_default',
        'include_reposts_default', 'translate_target_lang', 'translate_skip_langs',
        'x_account_region_enabled', 'x_community_notes_enabled'];
BEGIN
    IF TG_OP = 'DELETE' THEN
        IF OLD.key = ANY(relevant) THEN PERFORM igloo_sync_touch_head('setting', OLD.key); END IF;
        RETURN OLD;
    ELSIF TG_OP = 'UPDATE' THEN
        IF OLD.key IS NOT DISTINCT FROM NEW.key AND OLD.value IS NOT DISTINCT FROM NEW.value THEN
            RETURN NEW;
        END IF;
        IF OLD.key IS DISTINCT FROM NEW.key AND OLD.key = ANY(relevant) THEN
            PERFORM igloo_sync_touch_head('setting', OLD.key);
        END IF;
    END IF;
    IF NEW.key = ANY(relevant) THEN PERFORM igloo_sync_touch_head('setting', NEW.key); END IF;
    RETURN NEW;
END;
$$;
-- +goose StatementEnd

-- +goose StatementBegin
CREATE FUNCTION igloo_search_document(VARIADIC fields TEXT[]) RETURNS TSVECTOR
LANGUAGE plpgsql STABLE PARALLEL SAFE AS $$
DECLARE
    value TEXT;
    document TSVECTOR := ''::TSVECTOR;
BEGIN
    FOREACH value IN ARRAY fields LOOP
        -- A position gap keeps phrases within one field.
        document := document || (quote_literal(chr(31)) || ':1')::TSVECTOR ||
            to_tsvector('simple', regexp_replace(lower(unaccent(coalesce(value, '')) COLLATE "pg_c_utf8"), '[^[:alnum:]]+', ' ', 'g'));
    END LOOP;
    RETURN ts_delete(document, chr(31));
END;
$$;
-- +goose StatementEnd

-- +goose StatementBegin
CREATE FUNCTION igloo_search_query(value TEXT) RETURNS TSQUERY
LANGUAGE plpgsql STABLE PARALLEL SAFE AS $$
DECLARE
    term TEXT;
    tokens TEXT[];
    position INTEGER;
    query_text TEXT := '';
    term_query TEXT;
BEGIN
    FOREACH term IN ARRAY regexp_split_to_array(trim(value), '\s+') LOOP
        tokens := regexp_split_to_array(trim(regexp_replace(lower(unaccent(term) COLLATE "pg_c_utf8"), '[^[:alnum:]]+', ' ', 'g')), '\s+');
        term_query := '';
        FOR position IN 1..cardinality(tokens) LOOP
            IF tokens[position] <> '' THEN
                IF term_query <> '' THEN term_query := term_query || ' <-> '; END IF;
                term_query := term_query || quote_literal(tokens[position]);
                IF position = cardinality(tokens) THEN term_query := term_query || ':*'; END IF;
            END IF;
        END LOOP;
        IF term_query <> '' THEN
            IF query_text <> '' THEN query_text := query_text || ' & '; END IF;
            query_text := query_text || '(' || term_query || ')';
        END IF;
    END LOOP;
    RETURN query_text::TSQUERY;
END;
$$;
-- +goose StatementEnd

ALTER TABLE channels ADD COLUMN search_document TSVECTOR NOT NULL DEFAULT ''::TSVECTOR;
ALTER TABLE videos ADD COLUMN search_document TSVECTOR NOT NULL DEFAULT ''::TSVECTOR;
CREATE INDEX idx_channels_search_document ON channels USING GIN (search_document);
CREATE INDEX idx_videos_search_document ON videos USING GIN (search_document);
CREATE INDEX idx_feed_items_body_trigram ON feed_items USING GIN (body_text gin_trgm_ops);
CREATE INDEX idx_channel_profiles_handle_trigram ON channel_profiles USING GIN (handle gin_trgm_ops);
CREATE INDEX idx_channel_profiles_name_trigram ON channel_profiles USING GIN (display_name gin_trgm_ops);

-- +goose StatementBegin
CREATE FUNCTION igloo_search_owner_document() RETURNS TRIGGER
LANGUAGE plpgsql AS $$
DECLARE
    profile_name TEXT;
    profile_handle TEXT;
BEGIN
    PERFORM 1 FROM android_sync_clock WHERE id = 1 FOR UPDATE;
    IF TG_TABLE_NAME = 'channels' THEN
        SELECT display_name, handle INTO profile_name, profile_handle
        FROM channel_profiles WHERE channel_id = NEW.channel_id AND coalesce(tombstone, 0) = 0;
        NEW.search_document := igloo_search_document(NEW.name, NEW.source_id, profile_name, profile_handle);
    ELSE
        SELECT display_name INTO profile_name FROM channel_profiles WHERE channel_id = NEW.channel_id;
        NEW.search_document := igloo_search_document(NEW.title, NEW.dearrow_title, NEW.dearrow_title_casual, profile_name);
    END IF;
    RETURN NEW;
END;
$$;
-- +goose StatementEnd

-- +goose StatementBegin
CREATE FUNCTION igloo_search_profile_documents() RETURNS TRIGGER
LANGUAGE plpgsql AS $$
BEGIN
    IF TG_OP = 'UPDATE' AND
       ROW(OLD.channel_id, OLD.display_name, OLD.handle, OLD.tombstone) IS NOT DISTINCT FROM
       ROW(NEW.channel_id, NEW.display_name, NEW.handle, NEW.tombstone) THEN
        RETURN NULL;
    END IF;
    PERFORM 1 FROM android_sync_clock WHERE id = 1 FOR UPDATE;
    IF TG_OP <> 'INSERT' THEN
        UPDATE channels SET search_document = search_document WHERE channel_id = OLD.channel_id;
        UPDATE videos SET search_document = search_document WHERE channel_id = OLD.channel_id;
    END IF;
    IF TG_OP = 'INSERT' OR (TG_OP = 'UPDATE' AND OLD.channel_id IS DISTINCT FROM NEW.channel_id) THEN
        UPDATE channels SET search_document = search_document WHERE channel_id = NEW.channel_id;
        UPDATE videos SET search_document = search_document WHERE channel_id = NEW.channel_id;
    END IF;
    RETURN NULL;
END;
$$;
-- +goose StatementEnd

CREATE TRIGGER igloo_search_channels BEFORE INSERT OR UPDATE OF name, source_id, channel_id, search_document ON channels
FOR EACH ROW EXECUTE FUNCTION igloo_search_owner_document();
CREATE TRIGGER igloo_search_videos BEFORE INSERT OR UPDATE OF title, dearrow_title, dearrow_title_casual, channel_id, search_document ON videos
FOR EACH ROW EXECUTE FUNCTION igloo_search_owner_document();
CREATE TRIGGER igloo_search_profiles AFTER INSERT OR DELETE OR UPDATE OF channel_id, display_name, handle, tombstone ON channel_profiles
FOR EACH ROW EXECUTE FUNCTION igloo_search_profile_documents();

CREATE TRIGGER igloo_sync_feed_peers AFTER INSERT OR DELETE OR UPDATE OF content_hash, published_at ON feed_items
FOR EACH ROW EXECUTE FUNCTION igloo_sync_feed_peers('content_hash', 'direct', 'content_hash,published_at');
CREATE TRIGGER igloo_sync_quote_peers AFTER INSERT OR DELETE OR UPDATE OF quote_tweet_id, published_at ON feed_items
FOR EACH ROW EXECUTE FUNCTION igloo_sync_feed_peers('quote_tweet_id', 'lookup', 'quote_tweet_id,published_at');
CREATE TRIGGER igloo_sync_old_edges AFTER DELETE OR UPDATE OF quote_tweet_id, reply_to_status ON feed_items
FOR EACH ROW EXECUTE FUNCTION igloo_sync_feed_old_edges();
CREATE TRIGGER igloo_sync_retweet_peers AFTER INSERT OR DELETE OR UPDATE OF content_hash, retweeter_channel_id, tweet_id, published_at ON retweet_sources
FOR EACH ROW EXECUTE FUNCTION igloo_sync_feed_peers('content_hash', 'direct', 'content_hash,retweeter_channel_id,tweet_id,published_at');
CREATE TRIGGER igloo_sync_likes_protected AFTER INSERT OR DELETE OR UPDATE OF tweet_id ON feed_likes
FOR EACH ROW EXECUTE FUNCTION igloo_sync_protected_heads('tweet_id');
CREATE TRIGGER igloo_sync_bookmarks_protected AFTER INSERT OR DELETE OR UPDATE OF video_id ON bookmarks
FOR EACH ROW EXECUTE FUNCTION igloo_sync_protected_heads('video_id');
CREATE TRIGGER igloo_sync_likes_peers AFTER INSERT OR DELETE OR UPDATE OF tweet_id ON feed_likes
FOR EACH ROW EXECUTE FUNCTION igloo_sync_feed_peers('tweet_id', 'lookup', 'tweet_id');
CREATE TRIGGER igloo_sync_bookmarks_peers AFTER INSERT OR DELETE OR UPDATE OF video_id ON bookmarks
FOR EACH ROW EXECUTE FUNCTION igloo_sync_feed_peers('video_id', 'lookup', 'video_id');
CREATE TRIGGER igloo_sync_settings AFTER INSERT OR DELETE OR UPDATE OF key, value ON settings
FOR EACH ROW EXECUTE FUNCTION igloo_sync_setting_heads();


CREATE TRIGGER igloo_sync_head_channels AFTER INSERT OR DELETE OR UPDATE OF channel_id,source_id,name,url,platform ON channels
FOR EACH ROW EXECUTE FUNCTION igloo_sync_owner_head('channel', 'channel_id', 'channel_id,source_id,name,url,platform');

CREATE TRIGGER igloo_sync_head_channel_profiles AFTER INSERT OR DELETE OR UPDATE OF channel_id,platform,handle,display_name,bio,website,followers,following,verified,verified_type,account_region,account_details_json,protected,tombstone ON channel_profiles
FOR EACH ROW EXECUTE FUNCTION igloo_sync_owner_head('channel', 'channel_id', 'channel_id,platform,handle,display_name,bio,website,followers,following,verified,verified_type,account_region,account_details_json,protected,tombstone');

CREATE TRIGGER igloo_sync_head_feed_items AFTER INSERT OR DELETE OR UPDATE OF tweet_id,body_text,article_title,quote_article_title,lang,poll_json,quote_poll_json,community_note,quote_community_note,is_retweet,quote_tweet_id,quote_body_text,quote_lang,quote_media_json,media_json,canonical_url,reply_to_status,is_reply,is_ghost,quote_published_at,views,likes,retweets,published_at,content_hash,canonical_tweet_id,source_channel_id,channel_id,reposter_channel_id,quote_channel_id,reply_channel_id ON feed_items
FOR EACH ROW EXECUTE FUNCTION igloo_sync_owner_head('feed', 'tweet_id', 'tweet_id,body_text,article_title,quote_article_title,lang,poll_json,quote_poll_json,community_note,quote_community_note,is_retweet,quote_tweet_id,quote_body_text,quote_lang,quote_media_json,media_json,canonical_url,reply_to_status,is_reply,is_ghost,quote_published_at,views,likes,retweets,published_at,content_hash,canonical_tweet_id,source_channel_id,channel_id,reposter_channel_id,quote_channel_id,reply_channel_id');

CREATE TRIGGER igloo_sync_head_translations AFTER INSERT OR DELETE OR UPDATE OF tweet_id,field,source_lang,target_lang,translated_text,translated_at ON translations
FOR EACH ROW EXECUTE FUNCTION igloo_sync_owner_head('feed', 'tweet_id', 'tweet_id,field,source_lang,target_lang,translated_text,translated_at');

CREATE TRIGGER igloo_sync_head_videos AFTER INSERT OR DELETE OR UPDATE OF video_id,channel_id,owner_kind,title,description,duration,published_at,metadata_json,media_kind,slide_count,source_kind,dearrow_title,dearrow_title_casual,moments_all_position,moments_following_position ON videos
FOR EACH ROW EXECUTE FUNCTION igloo_sync_owner_head('video', 'video_id', 'video_id,channel_id,owner_kind,title,description,duration,published_at,metadata_json,media_kind,slide_count,source_kind,dearrow_title,dearrow_title_casual,moments_all_position,moments_following_position');

CREATE TRIGGER igloo_sync_head_video_comments AFTER INSERT OR DELETE OR UPDATE OF video_id,comment_id,parent_id,author_name,author_id,text,like_count,published_at ON video_comments
FOR EACH ROW EXECUTE FUNCTION igloo_sync_owner_head('video', 'video_id', 'video_id,comment_id,parent_id,author_name,author_id,text,like_count,published_at');

CREATE TRIGGER igloo_sync_head_video_repost_sources AFTER INSERT OR DELETE OR UPDATE OF video_id,reposter_channel_id,reposted_at_ms,first_seen_at_ms,updated_at_ms ON video_repost_sources
FOR EACH ROW EXECUTE FUNCTION igloo_sync_owner_head('video', 'video_id', 'video_id,reposter_channel_id,reposted_at_ms,first_seen_at_ms,updated_at_ms');

CREATE TRIGGER igloo_sync_head_sponsorblock_checked AFTER INSERT OR DELETE OR UPDATE OF video_id,checked_at,video_age_at_check ON sponsorblock_checked
FOR EACH ROW EXECUTE FUNCTION igloo_sync_owner_head('video', 'video_id', 'video_id,checked_at,video_age_at_check');

CREATE TRIGGER igloo_sync_head_sponsorblock_segments AFTER INSERT OR DELETE OR UPDATE OF video_id,start_time,end_time,category ON sponsorblock_segments
FOR EACH ROW EXECUTE FUNCTION igloo_sync_owner_head('video', 'video_id', 'video_id,start_time,end_time,category');

CREATE TRIGGER igloo_sync_head_retweet_sources AFTER INSERT OR DELETE OR UPDATE OF content_hash,retweeter_channel_id,tweet_id,published_at ON retweet_sources
FOR EACH ROW EXECUTE FUNCTION igloo_sync_owner_head('retweet_sources', 'content_hash', 'content_hash,retweeter_channel_id,tweet_id,published_at');

CREATE TRIGGER igloo_sync_head_feed_rank_snapshot AFTER INSERT OR DELETE OR UPDATE OF tweet_id,rank_position,base_score,decay_factor,freshness_bonus,jitter,diversity_demoted_by,final_score,computed_at ON feed_rank_snapshot
FOR EACH ROW EXECUTE FUNCTION igloo_sync_owner_head('feed_rank', 'tweet_id', 'tweet_id,rank_position,base_score,decay_factor,freshness_bonus,jitter,diversity_demoted_by,final_score,computed_at');

CREATE TRIGGER igloo_sync_head_assets AFTER INSERT OR DELETE OR UPDATE OF asset_id,asset_kind,owner_kind,owner_id,media_index,object_id,desired_object_id,lifecycle_state,revision,is_auto,audio_language,required_reason ON assets
FOR EACH ROW EXECUTE FUNCTION igloo_sync_owner_head('asset', 'asset_id', 'asset_id,asset_kind,owner_kind,owner_id,media_index,object_id,desired_object_id,lifecycle_state,revision,is_auto,audio_language,required_reason');

CREATE TRIGGER igloo_sync_head_feed_likes AFTER INSERT OR DELETE OR UPDATE OF tweet_id,liked_at ON feed_likes
FOR EACH ROW EXECUTE FUNCTION igloo_sync_owner_head('feed_like', 'tweet_id', 'tweet_id,liked_at');

CREATE TRIGGER igloo_sync_head_bookmarks AFTER INSERT OR DELETE OR UPDATE OF video_id,category_id,custom_title,account_handles,media_indices,bookmarked_at ON bookmarks
FOR EACH ROW EXECUTE FUNCTION igloo_sync_owner_head('bookmark', 'video_id', 'video_id,category_id,custom_title,account_handles,media_indices,bookmarked_at');

CREATE TRIGGER igloo_sync_head_bookmark_categories AFTER INSERT OR DELETE OR UPDATE OF id,name,archive_path,created_at ON bookmark_categories
FOR EACH ROW EXECUTE FUNCTION igloo_sync_owner_head('bookmark_category', 'id', 'id,name,archive_path,created_at');

CREATE TRIGGER igloo_sync_head_feed_seen AFTER INSERT OR DELETE OR UPDATE OF tweet_id,seen_at ON feed_seen
FOR EACH ROW EXECUTE FUNCTION igloo_sync_owner_head('feed_seen', 'tweet_id', 'tweet_id,seen_at');

CREATE TRIGGER igloo_sync_head_moment_views AFTER INSERT OR DELETE OR UPDATE OF video_id,viewed_at ON moment_views
FOR EACH ROW EXECUTE FUNCTION igloo_sync_owner_head('moment_view', 'video_id', 'video_id,viewed_at');

CREATE TRIGGER igloo_sync_head_watch_history AFTER INSERT OR DELETE OR UPDATE OF video_id,playback_position,duration,updated_at_ms ON watch_history
FOR EACH ROW EXECUTE FUNCTION igloo_sync_owner_head('watch_history', 'video_id', 'video_id,playback_position,duration,updated_at_ms');

CREATE TRIGGER igloo_sync_head_muted_channels AFTER INSERT OR DELETE OR UPDATE OF channel_id,muted_at ON muted_channels
FOR EACH ROW EXECUTE FUNCTION igloo_sync_owner_head('muted_channel', 'channel_id', 'channel_id,muted_at');

CREATE TRIGGER igloo_sync_head_channel_follows AFTER INSERT OR DELETE OR UPDATE OF channel_id,followed_at ON channel_follows
FOR EACH ROW EXECUTE FUNCTION igloo_sync_owner_head('channel_follow', 'channel_id', 'channel_id,followed_at');

CREATE TRIGGER igloo_sync_head_channel_stars AFTER INSERT OR DELETE OR UPDATE OF channel_id,starred_at ON channel_stars
FOR EACH ROW EXECUTE FUNCTION igloo_sync_owner_head('channel_star', 'channel_id', 'channel_id,starred_at');

CREATE TRIGGER igloo_sync_head_channel_settings AFTER INSERT OR DELETE OR UPDATE OF channel_id,media_only,include_reposts,media_download_limit,max_videos,download_subtitles,include_member_only,updated_at ON channel_settings
FOR EACH ROW EXECUTE FUNCTION igloo_sync_owner_head('channel_setting', 'channel_id', 'channel_id,media_only,include_reposts,media_download_limit,max_videos,download_subtitles,include_member_only,updated_at');

CREATE TRIGGER igloo_sync_head_moments_cursors AFTER INSERT OR DELETE OR UPDATE OF scope,video_id,position_ms,sort_at_ms,order_position,updated_at_ms ON moments_cursors
FOR EACH ROW EXECUTE FUNCTION igloo_sync_owner_head('moments_cursor', 'scope', 'scope,video_id,position_ms,sort_at_ms,order_position,updated_at_ms');

-- +goose Down

DROP VIEW feed_items_resolved;

DROP VIEW retweet_sources_resolved;

DROP VIEW video_repost_sources_resolved;

DROP TABLE youtube_recommendations;

DROP TABLE web_video_streams;

DROP TABLE video_metadata_jobs;

DROP TABLE profile_jobs;

DROP TABLE feed_item_sources;

DROP TABLE discover_temp_downloads;

DROP TABLE discover_refresh_anchors;

DROP TABLE auth_refresh_tokens;

DROP TABLE assets;

DROP TABLE youtube_broadcasts;

DROP TABLE watch_history;

DROP TABLE videos;

DROP TABLE video_repost_sources;

DROP TABLE video_fetch_history;

DROP TABLE video_desires;

DROP TABLE video_comments;

DROP TABLE translations;

DROP TABLE translation_jobs;

DROP TABLE temp_download_queue;

DROP TABLE sponsorblock_segments;

DROP TABLE sponsorblock_checked;

DROP TABLE settings;

DROP TABLE schema_migrations;

DROP TABLE retweet_sources;

DROP TABLE muted_channels;

DROP TABLE mutation_clocks;

DROP TABLE moments_order_history;

DROP TABLE moments_order_counters;

DROP TABLE moments_cursors;

DROP TABLE moment_views;

DROP TABLE media_objects;

DROP TABLE ingest_state;

DROP TABLE home_layouts;

DROP TABLE feed_sources;

DROP TABLE feed_share_token_affinity;

DROP TABLE feed_share_account_affinity;

DROP TABLE feed_seen;

DROP TABLE feed_rank_snapshot_history;

DROP TABLE feed_rank_snapshot;

DROP TABLE feed_order_invalidations;

DROP TABLE feed_likes;

DROP TABLE feed_items;

DROP TABLE downloader_operations;

DROP TABLE download_queue;

DROP TABLE discover_generation;

DROP TABLE channels;

DROP TABLE channel_stars;

DROP TABLE channel_settings;

DROP TABLE channel_profiles;

DROP TABLE channel_follows;

DROP TABLE category_create_receipts;

DROP TABLE bookmarks;

DROP TABLE bookmark_categories;

DROP TABLE auth_sessions;

DROP TABLE android_sync_health_reports;

DROP TABLE android_sync_heads;

DROP TABLE android_sync_clock;

DROP TABLE android_feed_retention;

DROP TABLE analytics_rollups_daily;

DROP TABLE analytics_events;

DROP FUNCTION igloo_sync_owner_head();
DROP FUNCTION igloo_sync_feed_peers();
DROP FUNCTION igloo_sync_feed_old_edges();
DROP FUNCTION igloo_sync_protected_heads();
DROP FUNCTION igloo_sync_setting_heads();
DROP FUNCTION igloo_sync_touch_feed_peers(TEXT);
DROP FUNCTION igloo_sync_touch_head(TEXT, TEXT);
DROP FUNCTION igloo_search_owner_document();
DROP FUNCTION igloo_search_profile_documents();
DROP FUNCTION igloo_search_document(TEXT[]);
DROP FUNCTION igloo_search_query(TEXT);
