package components

// Home labels shared with Android and the widget editor.
var _ = []string{
	N("nav_home", "Home"),
	N("home_continue", "Continue watching"),
	N("home_live", "Live"),
	N("home_starred", "Starred accounts"),
	N("home_moments", "Moments"),
	N("home_saved", "Saved"),
	N("home_account", "From an account"),
	N("home_latest", "Latest videos"),
	N("home_add_widget", "Add widget"),
	N("home_customize", "Customize"),
	N("home_widget_settings", "Widget settings"),
	N("home_size", "Size"),
	N("home_layout", "Layout"),
	N("home_style", "Style"),
	N("home_count", "Items"),
	N("home_platforms", "Platforms"),
	N("home_accounts", "Accounts"),
	N("home_content", "Content"),
	N("home_order", "Order"),
	N("home_spacing", "Spacing"),
	N("home_columns", "Columns"),
	N("home_title", "Title"),
	N("home_header", "Widget title"),
	N("home_media", "Media"),
	N("home_text", "Text"),
	N("home_starred_only", "Starred accounts only"),
	N("home_small", "Small"),
	N("home_medium", "Medium"),
	N("home_large", "Large"),
	N("home_full", "Full width"),
	N("home_feature", "Featured"),
	N("home_cards", "Cards"),
	N("home_list", "List"),
	N("home_editorial", "Editorial"),
	N("home_lanes", "Account lanes"),
	N("home_portraits", "Portraits"),
	N("home_surface", "Surface"),
	N("home_open", "Open"),
	N("home_accent", "Accent"),
	N("home_comfortable", "Comfortable"),
	N("home_compact", "Compact"),
	N("home_recent", "Recently watched"),
	N("home_recent_saved", "Recently saved"),
	N("home_newest", "Newest"),
	N("home_by_account", "By account"),
	N("home_live_now", "Live now"),
	N("home_upcoming", "Upcoming"),
	N("home_replays", "Replays"),
	N("home_post", "Posts"),
	N("home_video", "Videos"),
	N("home_image", "Photos"),
	N("home_slideshow", "Slideshows"),
	N("home_story", "Stories"),
	N("home_remove_widget", "Remove widget"),
	N("home_move_up", "Move up"),
	N("home_move_down", "Move down"),
	N("home_duplicate", "Duplicate widget"),
	N("home_empty", "No items"),
	N("home_sync_failed", "Could not save layout"),
	N("home_playback_failed", "Could not play the broadcast"),
	N("home_preview_failed", "Could not update preview"),
	N("home_discard", "Discard changes?"),
	N("home_discard_action", "Discard"),
	N("home_saved_layout", "Layout saved"),
	N("home_save_failed", "Could not save layout"),
	N("home_remove_confirm", "Remove widget?"),
	N("home_reset_confirm", "Reset layout?"),
}
