name: Nix CI

on:
  push:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  flake:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: DeterminateSystems/determinate-nix-action@v3

      - name: Check flake
        run: nix flake check --print-build-logs

      - name: Build container image
        run: nix build .#container --print-build-logs

      - name: Load container image
        run: docker load < result

      - name: Check container
        env:
          IGLOO_CONTAINER_CHECK_BUILD: "0"
          IGLOO_CONTAINER_CHECK_IMAGE: ghcr.io/screwys/igloo:latest
        run: scripts/dev/container-check.sh
